# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_seq.ipynb.

# %% auto #0
__all__ = ['BoosterModel', 'load_booster_model', 'load_seq_model', 'featurize_context', 'predict_seq']

# %% ../00_seq.ipynb #81a75f71
import json
import lightgbm as lgb
import sglearn
import pandas as pd
import os
from functools import lru_cache

# %% ../00_seq.ipynb #eb2ecc7d
class BoosterModel:
    """A LightGBM booster together with the feature contract it was trained on.

    rs3's models used to ship as pickles, two of them as scikit-learn Pipelines
    wrapping a median SimpleImputer. That bound the package to the 2021
    dependency stack: those pickles raise AttributeError on scikit-learn >= 1.2,
    and lightgbm's sklearn wrapper needs scikit-learn merely to call .predict().
    The models now ship as LightGBM's own text format plus a JSON sidecar, so
    nothing is version-coupled and scikit-learn is not a dependency at all.

    `predict` selects `feature_names` from the given DataFrame by name. That
    reindex is deliberate, and is the safety the sklearn wrapper used to
    provide: neither model file can validate its own inputs, because the target
    boosters record only Column_0..N (the imputer stripped the column names
    before fitting) and RuleSet3 records LightGBM-sanitised names ('GC_content'
    for the 'GC content' column). Selecting by name here means a change in
    upstream column order cannot silently mispredict.
    """

    def __init__(self, booster, feature_names, medians=None):
        self.booster = booster
        self.feature_names = list(feature_names)
        self.medians = (pd.Series(medians, index=self.feature_names)
                        if medians is not None else None)

    def predict(self, X):
        """Predict from a DataFrame carrying at least `feature_names`."""
        X = X[self.feature_names]
        if self.medians is not None:
            # Replaces the pickled SimpleImputer(strategy='median'); the medians
            # are the ones it had already fitted, so this is not a re-estimate.
            X = X.fillna(self.medians)
        return self.booster.predict(X.values)


@lru_cache(maxsize=None)
def load_booster_model(stem):
    """Load the booster and sidecar named `stem` from the rs3 package directory.

    Cached: RuleSet3 is ~17MB of model text and predict_seq is called per batch.
    """
    base = os.path.join(os.path.dirname(__file__), stem)
    with open(base + '.json') as f:
        sidecar = json.load(f)
    booster = lgb.Booster(model_file=base + '.txt')
    return BoosterModel(booster, sidecar['feature_names'], sidecar['medians'])


def load_seq_model():
    """Load rule set 3 sequence model"""
    return load_booster_model('RuleSet3')

# %% ../00_seq.ipynb #9065a434
def featurize_context(context_sequences, sequence_tracr='Hsu2013', ref_tracrs=None,
                      n_jobs=1):
    """Featurize context sequences

    :param context_sequences: list-like
    :param sequence_tracr: list-like or str
    :return: DataFrame, feature matrix
    """
    if ref_tracrs is None:
        ref_tracrs = ['Hsu2013', 'Chen2013']
    context_series = pd.Series(context_sequences)
    if not (context_series.str.len() == 30).all():
        raise  ValueError('All context sequences must be 30 nucleotides')
    featurized_sgrnas = sglearn.featurize_guides(context_sequences,
                                                 n_jobs=n_jobs)
    for tracr in ref_tracrs:
        if type(sequence_tracr) is str:
            featurized_sgrnas[tracr + ' tracr'] = int(sequence_tracr == tracr)
        else: # list-like
            featurized_sgrnas[tracr + ' tracr'] = ((pd.Series(sequence_tracr) == tracr)
                                                   .astype(int)
                                                   .to_list())
    return featurized_sgrnas

# %% ../00_seq.ipynb #5625581e
def predict_seq(context_sequences, sequence_tracr='Hsu2013', ref_tracrs=None, n_jobs=1):
    """Predict the activity of context sequence for SpCas9 Knockout using sequence information only

    :param context_sequences: list of str
    :return: list of float, predictions
    """
    model = load_seq_model()
    print('Calculating sequence-based features')
    featurized_sgrnas = featurize_context(context_sequences, sequence_tracr=sequence_tracr, ref_tracrs=ref_tracrs,
                                          n_jobs=n_jobs)
    seq_predictions = model.predict(featurized_sgrnas)
    return seq_predictions
